### ISSUE TITLE
Intellij idea import bug

### ISSUE THREAD

**Issue by heralight** [mean-expert-official/fireloop-todo-example#5]
Hi!

If I follow your tuturial http://mean.expert/2016/10/10/angular-2-real-time-applications/
I get 2 seperate folders, I can import them with no problem in my intellij IDE.
But with this repository where server is manage in root with some custom thing, I can't import it in intellij, this software doesn't recognize any framework and lock me out.

**Comment by jonathan-casarrubias** [comment]
Hi @heralight thanks for reporting

So, this repo has been built with the FireLoop CLI, which for convenience when using the loopback-generator is created into the root, following the same idea of having the clients on the root.

I don0t use Intellij so it would be just awesome if you help me figure out what needs to be done? is there a config file missing in the root to let intellij know this is a project? should we remove or modify an existing one?

Please share your thoughts.

Cheers
Jon

**Comment by heralight** [comment]
I try to fix this problem, and I found a solution.
we need to import project in intellij before do npm install on root.
I don't understand why node_modules in root specifically for this project, produce this bug, with only webapp directory no problem.
Strange.
I add a comment in readme about it in my pull request.
