### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sureshk2n** [mean-expert-official/fireloop-todo-example#9]
Hi
I just downloaded the zip file in windows and run npm run setup commands. After getting setup, running fireloop command started both client and server projects. When I browse localhost:4200 the page is loading with only a text box and date field. 

If I add some todo text, nothing works and no statistical chart is displaying. I don't see any data is stored in memory. checked in loopback explorer as well. Could you plz check and solve is this working or is there anything i am missing?

Thanks

**Comment by beeman** [comment]
Do you get any errors in the terminal or browser console?

**Comment by sureshk2n** [comment]
I get no error in terminal but i just checked in browser console. I am keep getting following error. It seems the url ip address is incorrect. it should be localhost or 127.0.0.1? If so plz tell me where to change.

GET http://0.0.0.0:3000/socket.io/?EIO=3&transport=polling&t=LfBwD43 net::ERR_ADDRESS_INVALID

Thanks

**Comment by beeman** [comment]
0.0.0.0 also points to localhost.  Are you sure the server is running?

Also check this issue https://github.com/mean-expert-official/fireloop-todo-example/issues/7

**Comment by beeman** [comment]
If that all does not work, search for 0.0.0.0 in the project to replace the IP address

**Comment by sureshk2n** [comment]
It is working after i set the ipaddress in webapp\src\app\shared\sdk\lb.config.ts
private static path: string = '//127.0.0.1:3000';

Thanks for your quick response.

**Comment by beeman** [comment]
Awesome!
